import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import {
  GlobalAuthProvider,
  LoadingMaskProvider,
  ReactScanProvider,
} from "@/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Exo Portal App",
  description: "Generated by yours truly",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <ReactScanProvider />
      <body className={`${inter.variable} antialiased bg-neutral-50`}>
        <NextIntlClientProvider messages={messages}>
          <GlobalAuthProvider />
          <LoadingMaskProvider />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
